name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image for testing
        run: docker build -t app/docker-react -f Dockerfile.dev .
      - name: Run tests
        run: docker run -e CI=true app/docker-react npm run test -- --coverage
